### ISSUE TITLE
Ideas on how to wrap Shmex.Native reads to a process?

### ISSUE THREAD

**Issue by eliasdarruda** [membraneframework/shmex#22]
I wanted to link `%Shmex{}` to a process and receive writes in my message queue using `receive` or `handle_info`.

Is this a valid use-case for Shmex?

**Comment by membraneframeworkadmin** [comment]
Issues related to membraneframework/shmex are stored in [membrane_core](https://github.com/membraneframework/membrane_core), so we close this issue here and we encourage you to open it [there](https://github.com/membraneframework/membrane_core).
